/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Uts_Mutiara.BankSwing;

/**
 *
 * @author ASUS
 */
public class Tranfer2 extends javax.swing.JFrame {

    /**
     * Creates new form Tranfer2
     */
    public Tranfer2() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jumtransfer = new javax.swing.JTextField();
        Benar = new javax.swing.JButton();
        salah = new javax.swing.JButton();
        sisa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ATM BANK MUTIARA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 40, 200, 22);

        jumtransfer.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jumtransferInputMethodTextChanged(evt);
            }
        });
        jPanel1.add(jumtransfer);
        jumtransfer.setBounds(100, 110, 190, 30);

        Benar.setText("Benar");
        Benar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BenarActionPerformed(evt);
            }
        });
        jPanel1.add(Benar);
        Benar.setBounds(310, 180, 80, 23);

        salah.setText("Salah");
        salah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salahActionPerformed(evt);
            }
        });
        jPanel1.add(salah);
        salah.setBounds(310, 210, 80, 23);

        sisa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sisa.setForeground(new java.awt.Color(255, 255, 255));
        sisa.setText("Sisa Saldo Anda");
        jPanel1.add(sisa);
        sisa.setBounds(10, 240, 300, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Masukkan Jumlah Transfer");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 80, 160, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BenarActionPerformed
        // TODO add your handling code here:
        TransferModel tf = new TransferModel();
        InformasiSaldoModel saldo = new InformasiSaldoModel();
        String jmlh = jumtransfer.getText();
        double jmlh2 = Double.parseDouble(jmlh);
        tf.transfer = jmlh2;
        double s = Double.parseDouble(saldo.getSaldo());
        double hasil = s- tf.transfer;
        if(tf != null){
            sisa.setVisible(true);
            sisa.setText("SISA SALDO ANDA : Rp "+hasil);
        }else{
            sisa.setVisible(false);}
    }//GEN-LAST:event_BenarActionPerformed

    private void jumtransferInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jumtransferInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jumtransferInputMethodTextChanged

    private void salahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salahActionPerformed
        // TODO add your handling code here:
        new Pinn().setVisible(true);
    }//GEN-LAST:event_salahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tranfer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tranfer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tranfer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tranfer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tranfer2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Benar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jumtransfer;
    private javax.swing.JButton salah;
    private javax.swing.JLabel sisa;
    // End of variables declaration//GEN-END:variables
}
